#!/bin/sh
set -e

/sbin/iptables-restore < /minit/iptables.v4
/sbin/ip6tables-restore < /minit/iptables.v6

/sbin/tunctl -t tap-ws0 -u wsvpn -g wsvpn
/sbin/ifconfig tap-ws0 10.0.0.1 netmask 255.0.0.0 mtu 1280 up

/bin/echo > /tmp/dhcpd.leases
/bin/chown dhcp:dhcp /tmp/dhcpd.leases


